# Generated by Django 2.0.6 on 2019-03-31 05:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.IntegerField(default=0)),
                ('keywords', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('alternate_titles', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('detail', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('cast_crew', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
